### ISSUE TITLE
SubscribeToExchangeDeltasAsync Issues

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#79]
I am having two issues with SubscribeToExchangeDeltasAsync:

1. It freezes my Windows Presentation Foundation (WPF) application if it's called without Task.Run method.  I would like to know proper way to call it. Maybe I am doing it wrong. It doesn't freeze the application if it's called with Task.Run method as shown in the code below.

2. It can't connect to Bittrex server with the latest Bittrex.Net v2.0.6.
It COULD connect to Bittrex server with version Bittrex.Net v2.0.5.

Code:
```
var client = new BittrexSocketClient();
var result = await Task.Run(() =>
{
  return client.SubscribeToExchangeDeltasAsync(marketName, data => Handler(data));
}).ConfigureAwait(false);
```
Error:
```
Success = false
Error.Message = Can't connect to the server
```
Log (with LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug):
```
10:39:34:429 | Warning | Couldn't connect. System.TypeLoadException
10:39:34:429 | Debug |  Couldn't load type 'CryptoExchange.Net.BaseSocket' from assembly 'CryptoExchange.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```
I'm using the latest CryptoExchange.Net (v0.0.10)

**Comment by JKorf** [comment]
Hi, the Bittrex.Net package needs a corresponding CryptoExchange.Net package. The latest Bittrex.Net version (v2.0.6) is based on CryptoExchange.Net version 0.0.9. Can you try downgrading to that version? The UI freeze should also be fixed in v2.0.6.

**Comment by pwnzya** [comment]
Hi. Thanks for quick response as always :)

With Bittrex.Net v2.0.6 and CryptoExchange.Net v0.0.9 it CAN connect to Bittrex server.
I should've been more careful about upgrading the libraries. Thanks.

However, it still freezes my WPF application if not called with the Task.Run method.
Maybe I am doing something wrong on my side...

Code below freezes the application:
```
var result = await client.SubscribeToExchangeDeltasAsync(marketName, data => Handler(data));
```

Code below doesn't freeze the application:
```
var result = await Task.Run(() =>
{
  return client.SubscribeToExchangeDeltasAsync(marketName, data => Handler(data));
}).ConfigureAwait(false);
```
By the way, I am OK with having to use the Task.Run method. I am only mentioning this since you seem to be trying to change the library so the users don't need to do this.

**Comment by JKorf** [comment]
I tested it, it freezes indeed. However call that's deadlocking is in a library I use (CloudFlareUtilities) so I can't change it directly. I opened an issue to see if they can fix it. Thanks for letting me know anyway :)

**Comment by pwnzya** [comment]
I see. I hope they can fix it :)
Closing this thread as your library is working fine.

**Comment by JKorf** [comment]
They were very helpful and fixed it last weekend. I pushed a new version (2.0.8) which should fix the freezing.
